-- Ejecuta en Supabase: SQL Editor o MCP
-- Proyecto: beoxjsnxausupnabuqtg

-- Tabla hoteles
CREATE TABLE IF NOT EXISTS public.hotels (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  location text NOT NULL,
  price numeric NOT NULL DEFAULT 0,
  rating numeric NOT NULL DEFAULT 0,
  reviews int NOT NULL DEFAULT 0,
  image text DEFAULT '',
  amenities jsonb DEFAULT '[]'::jsonb,
  stars int NOT NULL DEFAULT 0,
  description text DEFAULT '',
  tags jsonb DEFAULT '[]'::jsonb,
  "isSoldOut" boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Tabla reservaciones
CREATE TABLE IF NOT EXISTS public.reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Tabla perfiles (auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text,
  phone text,
  user_type text NOT NULL DEFAULT 'cliente' CHECK (user_type IN ('cliente', 'partner', 'admin')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Hoteles visibles para todos" ON public.hotels FOR SELECT USING (true);
CREATE POLICY "Cualquiera puede crear reservación" ON public.reservations FOR INSERT WITH CHECK (true);

CREATE POLICY "Usuarios ven su perfil" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Usuarios insertan su perfil" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Usuarios actualizan su perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone, user_type)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone',
    COALESCE(new.raw_user_meta_data->>'user_type', 'cliente')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
