-- Ejecuta este script en Supabase: SQL Editor → New query → Pegar → Run
-- Crea la tabla partners y vincula hoteles con partners (opción B + acceso con contraseña)

-- 1. Función para que solo admin pueda modificar (necesaria para RLS)
CREATE OR REPLACE FUNCTION public.current_user_is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- 2. Tabla partners (datos de contacto del hotel)
CREATE TABLE IF NOT EXISTS public.partners (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name text,
  email text,
  phone text,
  created_at timestamptz DEFAULT now()
);

-- 3. Columna para login del partner (opcional)
ALTER TABLE public.partners ADD COLUMN IF NOT EXISTS auth_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS partners_auth_user_id_key ON public.partners(auth_user_id) WHERE auth_user_id IS NOT NULL;

-- 4. RLS en partners
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Partners visibles para todos" ON public.partners;
CREATE POLICY "Partners visibles para todos" ON public.partners FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin puede insertar partners" ON public.partners;
CREATE POLICY "Admin puede insertar partners" ON public.partners FOR INSERT WITH CHECK (public.current_user_is_admin());

DROP POLICY IF EXISTS "Admin puede actualizar partners" ON public.partners;
CREATE POLICY "Admin puede actualizar partners" ON public.partners FOR UPDATE USING (public.current_user_is_admin());

DROP POLICY IF EXISTS "Admin puede eliminar partners" ON public.partners;
CREATE POLICY "Admin puede eliminar partners" ON public.partners FOR DELETE USING (public.current_user_is_admin());

-- 5. Quitar partner_id antiguo (uuid a auth.users) y usar bigint a partners
ALTER TABLE public.hotels DROP CONSTRAINT IF EXISTS hotels_partner_id_fkey;
ALTER TABLE public.hotels DROP COLUMN IF EXISTS partner_id;
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS partner_id bigint REFERENCES public.partners(id) ON DELETE SET NULL;

-- 6. Políticas de admin en hoteles (por si no existían)
DROP POLICY IF EXISTS "Admin puede insertar hoteles" ON public.hotels;
CREATE POLICY "Admin puede insertar hoteles" ON public.hotels FOR INSERT WITH CHECK (public.current_user_is_admin());
DROP POLICY IF EXISTS "Admin puede actualizar hoteles" ON public.hotels;
CREATE POLICY "Admin puede actualizar hoteles" ON public.hotels FOR UPDATE USING (public.current_user_is_admin());
