-- Soluciona: "new row violates row-level security policy" en galería de habitaciones.
-- Ejecuta en Supabase → SQL Editor (proyecto develop o producción).

-- 1) Función admin (igual que para hotel_images)
CREATE OR REPLACE FUNCTION public.current_user_is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- 2) Tabla room_images si no existe
CREATE TABLE IF NOT EXISTS public.room_images (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room_id bigint NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
  url text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  description text,
  url_medium text,
  url_small text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS room_images_room_id_idx ON public.room_images(room_id);
ALTER TABLE public.room_images ENABLE ROW LEVEL SECURITY;

-- 3) Políticas room_images (quitar las que existan y recrear)
DROP POLICY IF EXISTS "Admin puede ver galería de habitaciones" ON public.room_images;
DROP POLICY IF EXISTS "Admin puede insertar en galería habitaciones" ON public.room_images;
DROP POLICY IF EXISTS "Admin puede actualizar galería habitaciones" ON public.room_images;
DROP POLICY IF EXISTS "Admin puede eliminar de galería habitaciones" ON public.room_images;
DROP POLICY IF EXISTS "Público puede ver galería de habitaciones" ON public.room_images;

CREATE POLICY "Admin puede ver galería de habitaciones"
  ON public.room_images FOR SELECT USING (public.current_user_is_admin());
CREATE POLICY "Admin puede insertar en galería habitaciones"
  ON public.room_images FOR INSERT WITH CHECK (public.current_user_is_admin());
CREATE POLICY "Admin puede actualizar galería habitaciones"
  ON public.room_images FOR UPDATE USING (public.current_user_is_admin());
CREATE POLICY "Admin puede eliminar de galería habitaciones"
  ON public.room_images FOR DELETE USING (public.current_user_is_admin());
CREATE POLICY "Público puede ver galería de habitaciones"
  ON public.room_images FOR SELECT USING (true);

-- 4) Políticas Storage para bucket hotel-room-images
DROP POLICY IF EXISTS "Público puede ver imágenes de habitaciones" ON storage.objects;
DROP POLICY IF EXISTS "Admin puede subir imágenes de habitaciones" ON storage.objects;
DROP POLICY IF EXISTS "Admin puede eliminar imágenes de habitaciones" ON storage.objects;

CREATE POLICY "Público puede ver imágenes de habitaciones"
  ON storage.objects FOR SELECT USING (bucket_id = 'hotel-room-images');

CREATE POLICY "Admin puede subir imágenes de habitaciones"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'hotel-room-images' AND public.current_user_is_admin());

CREATE POLICY "Admin puede eliminar imágenes de habitaciones"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'hotel-room-images' AND public.current_user_is_admin());

-- 5) Dar rol admin a tu usuario (sustituye el email y ejecuta esta línea)
-- UPDATE public.profiles SET user_type = 'admin' WHERE email = 'TU_EMAIL@ejemplo.com';

-- 6) Crear el bucket en Dashboard si no existe: Storage → New bucket → nombre "hotel-room-images", Public = true.
