-- Galería de imágenes por habitación. Bucket: hotel-room-images (crear en Dashboard → Storage).
CREATE TABLE IF NOT EXISTS public.room_images (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room_id bigint NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
  url text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  description text,
  url_medium text,
  url_small text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS room_images_room_id_idx ON public.room_images(room_id);
COMMENT ON TABLE public.room_images IS 'URLs de imágenes de la galería de cada habitación (Storage bucket hotel-room-images).';

ALTER TABLE public.room_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin puede ver galería de habitaciones"
  ON public.room_images FOR SELECT USING (public.current_user_is_admin());
CREATE POLICY "Admin puede insertar en galería habitaciones"
  ON public.room_images FOR INSERT WITH CHECK (public.current_user_is_admin());
CREATE POLICY "Admin puede actualizar galería habitaciones"
  ON public.room_images FOR UPDATE USING (public.current_user_is_admin());
CREATE POLICY "Admin puede eliminar de galería habitaciones"
  ON public.room_images FOR DELETE USING (public.current_user_is_admin());

CREATE POLICY "Público puede ver galería de habitaciones"
  ON public.room_images FOR SELECT USING (true);

-- Storage: bucket "hotel-room-images" (crear en Dashboard → Storage → New bucket, Public = true).
CREATE POLICY "Público puede ver imágenes de habitaciones"
  ON storage.objects FOR SELECT USING (bucket_id = 'hotel-room-images');

CREATE POLICY "Admin puede subir imágenes de habitaciones"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'hotel-room-images' AND public.current_user_is_admin());

CREATE POLICY "Admin puede eliminar imágenes de habitaciones"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'hotel-room-images' AND public.current_user_is_admin());
