-- Opción B: Partner como datos de contacto del hotel (no como usuario del sistema)

-- Tabla de partners (datos de contacto)
CREATE TABLE IF NOT EXISTS public.partners (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name text,
  email text,
  phone text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

-- Todos pueden leer (para mostrar en detalle del hotel)
CREATE POLICY "Partners visibles para todos" ON public.partners FOR SELECT USING (true);
-- Solo admin puede insertar/actualizar/eliminar
CREATE POLICY "Admin puede insertar partners" ON public.partners FOR INSERT WITH CHECK (public.current_user_is_admin());
CREATE POLICY "Admin puede actualizar partners" ON public.partners FOR UPDATE USING (public.current_user_is_admin());
CREATE POLICY "Admin puede eliminar partners" ON public.partners FOR DELETE USING (public.current_user_is_admin());

-- Quitar partner_id que apuntaba a auth.users y usar tabla partners
ALTER TABLE public.hotels DROP CONSTRAINT IF EXISTS hotels_partner_id_fkey;
ALTER TABLE public.hotels DROP COLUMN IF EXISTS partner_id;

ALTER TABLE public.hotels ADD COLUMN partner_id bigint REFERENCES public.partners(id) ON DELETE SET NULL;
