-- Galería de imágenes por hotel. Las URLs apuntan a Supabase Storage (bucket hotel-images).
-- Antes de aplicar: en Dashboard → Storage → New bucket → nombre "hotel-images", Public = true.
CREATE TABLE IF NOT EXISTS public.hotel_images (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hotel_id bigint NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  url text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hotel_images_hotel_id_idx ON public.hotel_images(hotel_id);

COMMENT ON TABLE public.hotel_images IS 'URLs de imágenes de la galería de cada hotel (Storage).';

ALTER TABLE public.hotel_images ENABLE ROW LEVEL SECURITY;

-- Solo admins pueden gestionar la galería
CREATE POLICY "Admin puede ver galería de hoteles"
  ON public.hotel_images FOR SELECT
  USING (public.current_user_is_admin());

CREATE POLICY "Admin puede insertar en galería"
  ON public.hotel_images FOR INSERT
  WITH CHECK (public.current_user_is_admin());

CREATE POLICY "Admin puede actualizar galería"
  ON public.hotel_images FOR UPDATE
  USING (public.current_user_is_admin());

CREATE POLICY "Admin puede eliminar de galería"
  ON public.hotel_images FOR DELETE
  USING (public.current_user_is_admin());

-- Lectura pública para mostrar galería en la ficha del hotel
CREATE POLICY "Público puede ver galería de hoteles"
  ON public.hotel_images FOR SELECT
  USING (true);

-- Storage: bucket "hotel-images" (crear en Dashboard → Storage → New bucket, nombre: hotel-images, Public).
-- Políticas para que la app pueda subir/borrar y el público ver.
CREATE POLICY "Público puede ver imágenes de hoteles"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'hotel-images');

CREATE POLICY "Admin puede subir imágenes de hoteles"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'hotel-images'
    AND public.current_user_is_admin()
  );

CREATE POLICY "Admin puede eliminar imágenes de hoteles"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'hotel-images'
    AND public.current_user_is_admin()
  );
