-- partner_id en hoteles
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS partner_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;

-- Tabla habitaciones
CREATE TABLE IF NOT EXISTS public.rooms (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hotel_id bigint NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'ESTÁNDAR',
  price numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'DISPONIBLE' CHECK (status IN ('DISPONIBLE', 'OCUPADA', 'MANTENIMIENTO')),
  image text DEFAULT '',
  amenities jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Habitaciones visibles para todos" ON public.rooms FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION public.current_user_is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

CREATE POLICY "Admin puede insertar hoteles" ON public.hotels FOR INSERT WITH CHECK (public.current_user_is_admin());
CREATE POLICY "Admin puede actualizar hoteles" ON public.hotels FOR UPDATE USING (public.current_user_is_admin());
CREATE POLICY "Admin puede insertar habitaciones" ON public.rooms FOR INSERT WITH CHECK (public.current_user_is_admin());
CREATE POLICY "Admin puede actualizar habitaciones" ON public.rooms FOR UPDATE USING (public.current_user_is_admin());
CREATE POLICY "Admin puede eliminar habitaciones" ON public.rooms FOR DELETE USING (public.current_user_is_admin());

-- Seed: 20 hoteles de México + 10 habitaciones (solo si están vacías)
INSERT INTO public.hotels (name, location, price, rating, reviews, image, amenities, stars, description, tags, "isSoldOut")
SELECT * FROM (VALUES
  ('Grand Fiesta Americana Coral Beach', 'Cancún, Quintana Roo', 320, 4.8, 2100, 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400', '["Alberca","Spa","Wifi","Estacionamiento"]'::jsonb, 5, 'Resort frente al mar en Zona Hotelera.', '["playa","lujo"]'::jsonb, false),
  ('Hotel Marriott CasaMagna', 'Cancún, Quintana Roo', 180, 4.5, 3200, 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400', '["Alberca","Gimnasio","Wifi"]'::jsonb, 5, 'Hotel de playa con vista al Caribe.', '["playa","familia"]'::jsonb, false),
  ('Hyatt Regency México', 'Ciudad de México', 150, 4.6, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400', '["Wifi","Restaurante","Bar"]'::jsonb, 5, 'Ubicado en Polanco.', '["ciudad","negocios"]'::jsonb, false),
  ('Casa de Sierra Nevada', 'San Miguel de Allende, Gto.', 280, 4.9, 890, 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=400', '["Spa","Restaurante","Jardín"]'::jsonb, 5, 'Boutique en centro histórico.', '["boutique","romántico"]'::jsonb, false),
  ('Villa del Palmar Flamingos', 'Puerto Vallarta, Jal.', 220, 4.4, 1500, 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400', '["Alberca","Playa","Spa"]'::jsonb, 5, 'Resort todo incluido en Bahía de Banderas.', '["playa","todo-incluido"]'::jsonb, false),
  ('Hotel Escondido', 'Puerto Escondido, Oax.', 190, 4.7, 420, 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=400', '["Playa","Wifi","Restaurante"]'::jsonb, 4, 'Ecolodge frente al Pacífico.', '["playa","ecológico"]'::jsonb, false),
  ('Las Ventanas al Paraíso', 'Los Cabos, BCS', 850, 4.9, 1200, 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400', '["Spa","Golf","Alberca","Privacidad"]'::jsonb, 5, 'Resort de lujo en el Corredor.', '["lujo","playa"]'::jsonb, false),
  ('Hacienda Xcanatún', 'Mérida, Yuc.', 240, 4.8, 650, 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=400', '["Spa","Restaurante","Piscina"]'::jsonb, 5, 'Hacienda colonial con spa.', '["colonial","spa"]'::jsonb, false),
  ('Hotel Matilda', 'San Miguel de Allende, Gto.', 320, 4.8, 720, 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400', '["Spa","Arte","Restaurante"]'::jsonb, 5, 'Arte y diseño en el centro.', '["boutique","arte"]'::jsonb, false),
  ('Banyan Tree Mayakoba', 'Playa del Carmen, Q.Roo', 620, 4.9, 980, 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400', '["Villa privada","Spa","Alberca"]'::jsonb, 5, 'Villas con alberca privada en Mayakoba.', '["lujo","spa"]'::jsonb, false),
  ('Quinta Real Oaxaca', 'Oaxaca, Oax.', 200, 4.7, 540, 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400', '["Convento","Restaurante","Jardín"]'::jsonb, 5, 'Ex convento en el centro.', '["histórico","boutique"]'::jsonb, false),
  ('Hotel Habita Monterrey', 'Monterrey, NL', 140, 4.5, 1100, 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400', '["Rooftop","Gimnasio","Wifi"]'::jsonb, 4, 'Diseño contemporáneo en San Pedro.', '["ciudad","diseño"]'::jsonb, false),
  ('Villa del Arco Cabo', 'Cabo San Lucas, BCS', 260, 4.6, 2100, 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400', '["Alberca","Spa","Playa"]'::jsonb, 5, 'Resort en la Marina.', '["playa","familia"]'::jsonb, false),
  ('Casa Oaxaca', 'Oaxaca, Oax.', 180, 4.8, 380, 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=400', '["Terraza","Restaurante","Centro"]'::jsonb, 4, 'Pequeño hotel en el centro.', '["boutique","gastronomía"]'::jsonb, false),
  ('Hotel Marqués Reforma', 'Ciudad de México', 165, 4.6, 950, 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400', '["Wifi","Restaurante","Bar"]'::jsonb, 5, 'Sobre Paseo de la Reforma.', '["ciudad","negocios"]'::jsonb, false),
  ('One&Only Palmilla', 'Los Cabos, BCS', 920, 4.9, 750, 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400', '["Golf","Spa","Playa privada"]'::jsonb, 5, 'Resort de lujo en Palmilla.', '["lujo","golf"]'::jsonb, false),
  ('Hotel Azul Tulum', 'Tulum, Q.Roo', 210, 4.5, 620, 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400', '["Playa","Ecológico","Yoga"]'::jsonb, 4, 'Eco-hotel en la zona hotelera.', '["playa","eco"]'::jsonb, false),
  ('Casa de los Sueños', 'Isla Mujeres, Q.Roo', 290, 4.7, 410, 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400', '["Playa","Spa","Restaurante"]'::jsonb, 5, 'Boutique frente al mar.', '["playa","boutique"]'::jsonb, false),
  ('Hacienda de los Santos', 'Álamos, Son.', 195, 4.8, 320, 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=400', '["Pueblo mágico","Spa","Restaurante"]'::jsonb, 5, 'Hacienda en pueblo mágico.', '["colonial","pueblo mágico"]'::jsonb, false),
  ('Hotel Esencia', 'Riviera Maya, Q.Roo', 720, 4.9, 280, 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400', '["Playa privada","Spa","Gastronomía"]'::jsonb, 5, 'Mansión convertida en hotel de lujo.', '["lujo","playa"]'::jsonb, false)
) AS v(name, location, price, rating, reviews, image, amenities, stars, description, tags, "isSoldOut")
WHERE NOT EXISTS (SELECT 1 FROM public.hotels LIMIT 1);

-- 10 habitaciones de ejemplo para el primer hotel (solo si rooms está vacío)
INSERT INTO public.rooms (hotel_id, name, type, price, status, image, amenities)
SELECT h.id, r.name, r.type, r.price, r.status, r.image, r.amenities
FROM public.hotels h
CROSS JOIN (VALUES
  ('Suite Presidencial', 'SUITE DE LUJO', 450, 'DISPONIBLE', 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400', '["Wifi","Clima","Jacuzzi","4K Smart TV"]'::jsonb),
  ('Doble Vista Mar', 'DOBLE DELUXE', 280, 'OCUPADA', 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400', '["Wifi","Minibar","Balcón"]'::jsonb),
  ('Estándar Jardín', 'ESTÁNDAR', 150, 'MANTENIMIENTO', 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=400', '["Wifi","Café"]'::jsonb),
  ('Junior Suite', 'SUITE', 320, 'DISPONIBLE', 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=400', '["Wifi","Balcón","Sofá"]'::jsonb),
  ('Penthouse', 'PREMIUM', 850, 'OCUPADA', 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400', '["Privacidad","Bar","Pool"]'::jsonb),
  ('Doble Queen', 'ESTÁNDAR', 180, 'DISPONIBLE', 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=400', '["Wifi","4K Smart TV","Desk"]'::jsonb),
  ('Suite Ejecutiva', 'SUITE', 380, 'DISPONIBLE', 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400', '["Wifi","Minibar","Sala"]'::jsonb),
  ('Vista Mar Deluxe', 'DOBLE DELUXE', 260, 'DISPONIBLE', 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=400', '["Wifi","Balcón","Clima"]'::jsonb),
  ('Estándar Doble', 'ESTÁNDAR', 140, 'DISPONIBLE', 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400', '["Wifi","Café"]'::jsonb),
  ('Suite Familiar', 'SUITE', 420, 'MANTENIMIENTO', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400', '["Wifi","Sofá cama","Clima"]'::jsonb)
) AS r(name, type, price, status, image, amenities)
WHERE h.id = (SELECT MIN(id) FROM public.hotels)
AND NOT EXISTS (SELECT 1 FROM public.rooms LIMIT 1);
