-- Catálogo de amenidades para hoteles (lista maestra para filtros y asignación)
CREATE TABLE IF NOT EXISTS public.amenity_catalog (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  label text NOT NULL,
  category text NOT NULL DEFAULT 'general',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.amenity_catalog IS 'Catálogo maestro de amenidades; los hoteles usan el slug en hotels.amenities (jsonb array).';
COMMENT ON COLUMN public.amenity_catalog.slug IS 'Identificador único para código y filtros (ej. wifi, alberca).';
COMMENT ON COLUMN public.amenity_catalog.label IS 'Texto para mostrar en la UI (ej. WiFi, Alberca).';
COMMENT ON COLUMN public.amenity_catalog.category IS 'Agrupación para filtros: conectividad, alberca_playa, bienestar, comida, habitacion, servicios, familia, deportes, accesibilidad.';

ALTER TABLE public.amenity_catalog ENABLE ROW LEVEL SECURITY;

-- Lectura: cualquier usuario autenticado (y anon para búsquedas públicas si se usa en front)
CREATE POLICY "amenity_catalog_select" ON public.amenity_catalog FOR SELECT USING (true);

-- Escritura: solo admin
CREATE POLICY "amenity_catalog_insert_admin" ON public.amenity_catalog FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin'));

CREATE POLICY "amenity_catalog_update_admin" ON public.amenity_catalog FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin'));

CREATE POLICY "amenity_catalog_delete_admin" ON public.amenity_catalog FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin'));

-- Seed: amenidades comunes para hoteles generales (por categoría)
INSERT INTO public.amenity_catalog (slug, label, category, sort_order) VALUES
-- Conectividad
('wifi', 'WiFi', 'conectividad', 10),
('wifi_gratis', 'WiFi gratuito', 'conectividad', 11),
('business_center', 'Centro de negocios', 'conectividad', 12),
('salas_reuniones', 'Salas de reuniones', 'conectividad', 13),
-- Alberca y wellness
('alberca', 'Alberca / Piscina', 'alberca_wellness', 20),
('alberca_exterior', 'Alberca exterior', 'alberca_wellness', 21),
('alberca_interior', 'Alberca interior', 'alberca_wellness', 22),
('spa', 'Spa', 'alberca_wellness', 23),
('gimnasio', 'Gimnasio', 'alberca_wellness', 24),
('jacuzzi', 'Jacuzzi', 'alberca_wellness', 25),
('sauna', 'Sauna', 'alberca_wellness', 26),
-- Comida y bebida
('restaurante', 'Restaurante', 'comida_bebida', 30),
('bar', 'Bar', 'comida_bebida', 31),
('room_service', 'Servicio a la habitación', 'comida_bebida', 32),
('desayuno_incluido', 'Desayuno incluido', 'comida_bebida', 33),
('mini_bar', 'Minibar', 'comida_bebida', 34),
('cafeteria', 'Cafetería', 'comida_bebida', 35),
-- Habitación
('aire_acondicionado', 'Aire acondicionado', 'habitacion', 40),
('calefaccion', 'Calefacción', 'habitacion', 41),
('tv', 'TV', 'habitacion', 42),
('caja_fuerte', 'Caja fuerte', 'habitacion', 43),
('balcon', 'Balcón', 'habitacion', 44),
('secador_pelo', 'Secador de pelo', 'habitacion', 45),
-- Servicios
('estacionamiento', 'Estacionamiento', 'servicios', 50),
('estacionamiento_gratis', 'Estacionamiento gratuito', 'servicios', 51),
('recepcion_24h', 'Recepción 24 h', 'servicios', 52),
('concierge', 'Concierge', 'servicios', 53),
('lavanderia', 'Lavandería', 'servicios', 54),
('traslado_aeropuerto', 'Traslado al aeropuerto', 'servicios', 55),
('tour_desk', 'Tour desk', 'servicios', 56),
-- Familia y mascotas
('pet_friendly', 'Acepta mascotas', 'familia_mascotas', 60),
('club_infantil', 'Club infantil', 'familia_mascotas', 61),
('cunas', 'Cunas', 'familia_mascotas', 62),
-- Deportes
('cancha_tenis', 'Cancha de tenis', 'deportes', 70),
('golf', 'Campo de golf', 'deportes', 71),
('bicicletas', 'Bicicletas', 'deportes', 72),
-- Accesibilidad
('elevador', 'Elevador', 'accesibilidad', 80),
('accesible_silla_ruedas', 'Accesible silla de ruedas', 'accesibilidad', 81)
ON CONFLICT (slug) DO NOTHING;
